### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by xhaross** [Lil-Jie/Wound-Detection-App-NUSRI#1]
![Untitled](https://user-images.githubusercontent.com/68476431/121457022-30435900-c9d1-11eb-9ac9-2e4e7f3cafe6.png)
i have try your code and get some error. cannot see result of my image. please help

**Comment by xhaross** [comment]
[INFO   ] Logger: Record log in C:\Users\xharo\.kivy\logs\kivy_21-06-10_0.txt
[INFO   ] deps: Successfully imported "kivy_deps.angle" 0.3.0
[INFO   ] deps: Successfully imported "kivy_deps.glew" 0.3.0
[INFO   ] deps: Successfully imported "kivy_deps.sdl2" 0.3.1
[INFO   ] Kivy: v2.0.0
[INFO   ] Kivy: Installed at "D:\python\Wound-Detection-App-NUSRI-main\Wound App\kivy_venv\lib\site-packages\kivy\__init__.py"
[INFO   ] Python: v3.8.5 (tags/v3.8.5:580fbb0, Jul 20 2020, 15:57:54) [MSC v.1924 64 bit (AMD64)]
[INFO   ] Python: Interpreter at "D:\python\Wound-Detection-App-NUSRI-main\Wound App\kivy_venv\Scripts\python.exe"
[INFO   ] Factory: 186 symbols loaded
[INFO   ] Image: Providers: img_tex, img_dds, img_sdl2, img_pil (img_ffpyplayer ignored)
[INFO   ] Window: Provider: sdl2
[INFO   ] GL: Using the "OpenGL" graphics system
[INFO   ] GL: GLEW initialization succeeded
[INFO   ] GL: Backend used <glew>
[INFO   ] GL: OpenGL version <b'4.4.0 - Build 20.19.15.4531'>
[INFO   ] GL: OpenGL vendor <b'Intel'>
[INFO   ] GL: OpenGL renderer <b'Intel(R) HD Graphics 5500'>
[INFO   ] GL: OpenGL parsed version: 4, 4
[INFO   ] GL: Shading version <b'4.40 - Build 20.19.15.4531'>
[INFO   ] GL: Texture max size <16384>
[INFO   ] GL: Texture max units <32>
[INFO   ] Window: auto add sdl2 input provider
[INFO   ] Window: virtual keyboard not allowed, single mode, not docked
[INFO   ] KivyMD: 0.104.2.dev0 (installed at "D:\python\Wound-Detection-App-NUSRI-main\Wound App\kivymd\__init__.py")
[INFO   ] Text: Provider: sdl2
[INFO   ] GL: NPOT texture support is available
[INFO   ] Base: Start application main loop
[INFO   ] Loader: using a thread pool of 2 workers
[ERROR  ] AsyncImage: Not found <appimage/wound_eg.jpg>
[ERROR  ] AsyncImage: Not found <appimage/wound_eg.jpg>
[ERROR  ] AsyncImage: Not found <appimage/result_eg.jpg>
[ERROR  ] AsyncImage: Not found <appimage/result_eg.jpg>
[ERROR  ] AsyncImage: Not found <D:/PythonProject/APPupdate/appimage/splash1.jpg>
[ERROR  ] AsyncImage: Not found <appimage/wound_eg.jpg>
[ERROR  ] AsyncImage: Not found <appimage/wound_eg.jpg>
[ERROR  ] AsyncImage: Not found <appimage/wound_eg.jpg>
[ERROR  ] AsyncImage: Not found <appimage/wound_eg.jpg>
[INFO   ] GL: Unpack subimage support is available
[INFO   ] Base: Leaving application in progress...
[WARNING] stderr: Traceback (most recent call last):
[WARNING] stderr:   File "main.py", line 99, in <module>
[WARNING] stderr:     recite_app.run()
[WARNING] stderr:   File "D:\python\Wound-Detection-App-NUSRI-main\Wound App\kivy_venv\lib\site-packages\kivy\app.py", line 950, in run
[WARNING] stderr:     runTouchApp()
[WARNING] stderr:   File "D:\python\Wound-Detection-App-NUSRI-main\Wound App\kivy_venv\lib\site-packages\kivy\base.py", line 582, in runTouchApp
[WARNING] stderr:     EventLoop.mainloop()
[WARNING] stderr:   File "D:\python\Wound-Detection-App-NUSRI-main\Wound App\kivy_venv\lib\site-packages\kivy\base.py", line 347, in mainloop
[WARNING] stderr:     self.idle()
[WARNING] stderr:   File "D:\python\Wound-Detection-App-NUSRI-main\Wound App\kivy_venv\lib\site-packages\kivy\base.py", line 391, in idle
[WARNING] stderr:     self.dispatch_input()
[WARNING] stderr:   File "D:\python\Wound-Detection-App-NUSRI-main\Wound App\kivy_venv\lib\site-packages\kivy\base.py", line 342, in dispatch_input
[WARNING] stderr:     post_dispatch_input(*pop(0))
[WARNING] stderr:   File "D:\python\Wound-Detection-App-NUSRI-main\Wound App\kivy_venv\lib\site-packages\kivy\base.py", line 308, in post_dispatch_input
[WARNING] stderr:     wid.dispatch('on_touch_up', me)
[WARNING] stderr:   File "kivy\_event.pyx", line 709, in kivy._event.EventDispatcher.dispatch
[WARNING] stderr:   File "D:\python\Wound-Detection-App-NUSRI-main\Wound App\kivymd\uix\behaviors\ripple_behavior.py", line 296, in on_touch_up
[WARNING] stderr:     return super().on_touch_up(touch)
[WARNING] stderr:   File "D:\python\Wound-Detection-App-NUSRI-main\Wound App\kivy_venv\lib\site-packages\kivy\uix\behaviors\button.py", line 179, in on_touch_up
[WARNING] stderr:     self.dispatch('on_release')
[WARNING] stderr:   File "kivy\_event.pyx", line 705, in kivy._event.EventDispatcher.dispatch
[WARNING] stderr:   File "kivy\_event.pyx", line 1248, in kivy._event.EventObservers.dispatch
[WARNING] stderr:   File "kivy\_event.pyx", line 1132, in kivy._event.EventObservers._dispatch
[WARNING] stderr:   File "D:\python\Wound-Detection-App-NUSRI-main\Wound App\kivy_venv\lib\site-packages\kivy\lang\builder.py", line 57, in custom_callback
[WARNING] stderr:     exec(__kvlang__.co_value, idmap)
[WARNING] stderr:   File "D:\python\Wound-Detection-App-NUSRI-main\Wound App\pages\homepage\homepage.kv", line 98, in <module>
[WARNING] stderr:     on_release: root.show_result()
[WARNING] stderr:   File "D:\python\Wound-Detection-App-NUSRI-main\Wound App\pages\homepage\homepage.py", line 73, in show_result
[WARNING] stderr:     post_analysis(file)
[WARNING] stderr:   File "D:\python\Wound-Detection-App-NUSRI-main\Wound App\tf_analysis\tf_analysis.py", line 15, in post_analysis
[WARNING] stderr:     model = unet()
[WARNING] stderr:   File "D:\python\Wound-Detection-App-NUSRI-main\Wound App\tf_analysis\model.py", line 59, in unet
[WARNING] stderr:     model = Model(input=inputs, output=conv10)
[WARNING] stderr:   File "D:\python\Wound-Detection-App-NUSRI-main\Wound App\kivy_venv\lib\site-packages\tensorflow\python\training\tracking\base.py", line 522, in _method_wrapper
[WARNING] stderr:     result = method(self, *args, **kwargs)
[WARNING] stderr:   File "D:\python\Wound-Detection-App-NUSRI-main\Wound App\kivy_venv\lib\site-packages\keras\engine\training.py", line 242, in __init__
[WARNING] stderr:     generic_utils.validate_kwargs(kwargs, {
[WARNING] stderr:   File "D:\python\Wound-Detection-App-NUSRI-main\Wound App\kivy_venv\lib\site-packages\keras\utils\generic_utils.py", line 1134, in validate_kwargs
[WARNING] stderr:     raise TypeError(error_message, kwarg)
[WARNING] stderr: TypeError: ('Keyword argument not understood:', 'input')

**Comment by Lil-Jie** [comment]
Hi,

First of all, I wonder what is the direction of the project you are working now

And please retell your problems encountered in reimplementing the code in details.

发送自 Windows 10 版邮件应用

发件人: xhaross
发送时间: 2021年6月10日 10:51
收件人: Lil-Jie/Wound-Detection-App-NUSRI
抄送: Subscribed
主题: [Lil-Jie/Wound-Detection-App-NUSRI] need help (#1)


i have try your code and get some error. cannot see result of my image. please help

**Comment by xhaross** [comment]
i am learning how the logic of cv2 and tensorflow working to calculate wound area. i need your project to my paper. can you share your full project to my email?
xha.ross@gmail.com

thank you

**Comment by Lil-Jie** [comment]
All right,

Actually, what you’ve download is all my project code just without the model I’ve trained since it’s too large to upload and needs improvement. Thus, for your project, u can try my u-net model architecture to train your own model according to your wound images.

And for the logic of calculate wound area, first use tf to detect the wound area and extract the wound contour, then use cv2.contourArea to calculate the area, but the result is shown as pixel value. And that’s why I am still further this study to make it to be actual value like cm2 or m2.

I’m glad if u have any questions about my project, just email me. But hope to make it more specific like a certain part. If u just run my code, it will definitely get wrong since our environment or other configuration is not the same.

By the way, are u a student or other occupation?

发送自 Windows 10 版邮件应用

发件人: xhaross
发送时间: 2021年6月10日 15:43
收件人: Lil-Jie/Wound-Detection-App-NUSRI
抄送: Lil-Jie; Comment
主题: Re: [Lil-Jie/Wound-Detection-App-NUSRI] need help (#1)

i am learning how the logic of cv2 and tensorflow working to calculate wound area. i need your project to my paper. can you share your full project to my email?
***@***.***
thank you

**Comment by xhaross** [comment]
this is what happen when i run your project. any idea?

https://user-images.githubusercontent.com/68476431/121493207-cb542700-ca01-11eb-93ea-c9ae14f3b039.mp4

**Comment by Lil-Jie** [comment]
Because u haven’t train your own model, before training the dataset, you have to load the weight from the trained model.

发送自 Windows 10 版邮件应用

发件人: xhaross
发送时间: 2021年6月10日 16:38
收件人: Lil-Jie/Wound-Detection-App-NUSRI
抄送: Lil-Jie; Comment
主题: Re: [Lil-Jie/Wound-Detection-App-NUSRI] need help (#1)

this is what happen when i run your project. any idea?
https://user-images.githubusercontent.com/68476431/121493207-cb542700-ca01-11eb-93ea-c9ae14f3b039.mp4

**Comment by xhaross** [comment]
Would you share your hdf5 file? I cannot train my own dataset. Thank you

**Comment by xhaross** [comment]
Would you share your hdf5 file? I cannot train my own dataset. Thank you

**Comment by xhaross** [comment]
few days i try to learn create hdf5 file and everything i need. but i am still enable to  run properly. i need your hdf5 file. i need more learn and practice. here i got form my hdf5 file that i create

ValueError: You are trying to load a weight file containing 31 layers into a model with 24 layers.

please help. thank you
